### ISSUE TITLE
The Demo is not working

### ISSUE THREAD

**Issue by dewanganlakhan** [mattmezza/bulmahead#1]
Hey, I have check the Demo on latest Chrome and Firefox, but its not working. 
I tried to debug or check if we have any errors on console but couldn't found any.

![bulmahead](https://user-images.githubusercontent.com/309298/46964946-0bcf3b80-d0c7-11e8-87c5-8a6413b1bd31.PNG)

**Comment by mattmezza** [comment]
Hi there, just tried on Safari, works like a charm. I notice you wrote `alba` instead of `alaba`, probably that's the mistake?

Let me know and have a nice day.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1915989/46965243-935a8180-d0aa-11e8-8fff-89cff1b68c36.png">

**Comment by dewanganlakhan** [comment]
Working Thanks
