### ISSUE TITLE
On keydown/up focus next dropdown item

### ISSUE THREAD

**Issue by b3ade** [mattmezza/bulmahead#14]
After entering first letters and dropdown menu is open, it will be nice to have keyboard focus navigation trough dropdown-items by pressing up/down. On focused element and pressing enter submit selected item.

**Comment by moomoohk** [comment]
Hi
I've implemented this behavior in my personal fork of Bulmahead (on the `timeline` branch): https://github.com/moomoohk/bulmahead/tree/timeline
It's by no means production ready but works well enough for my personal uses
You can use it in your project like so: 
`<script src="https://raw.githack.com/moomoohk/bulmahead/timeline/dist/bulmahead.bundle.js"></script>`

I might create a pull request in the future
