### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by SamCreamer** [mattmezza/bulmahead#3]
Sorry if this is not helpful... This may be related to my browser or something, but I just can't get the demo to work. I've tried the one on your sample page and have downloaded the source and tried to configure it myself. I typed out `texas` completely without seeing anything. Tried in Firefox and Safari.

**Comment by mattmezza** [comment]
Hi, thanks for stopping by. 

I think the component is case sensitive so you probably have to type `Tex` for Texas to show up. 

If you write `tex`, you don’t get suggestions. 

I hope this helps. 

I’ll merge a PR that removes the case sensitivity (the best would be to use fuzzy search). 

Regards,
 Matt.
