### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by janat08** [mattmezza/bulmahead#5]

**Comment by mattmezza** [comment]
What? ;)

**Comment by janat08** [comment]
The demo isn't working on Firefox.

**Comment by chetanc97** [comment]
Yup same on chrome

**Comment by mattmezza** [comment]
![Screen Shot 2019-12-11 at 9 49 36 AM](https://user-images.githubusercontent.com/1915989/70605884-9fcd6200-1bfb-11ea-844f-0654d6beb06d.png)

The suggestions are not case insensitive. Maybe they should be though ...

**Comment by jfschaff** [comment]
Same here, the demo available @ http://matteo.merola.co/bulmahead/ is not working for me on Chrome or FF.

I get this in the Chrome console (don't know if it may be related):
<img width="630" alt="image" src="https://user-images.githubusercontent.com/25389614/106147483-32222380-6178-11eb-99ca-d392e0d690c4.png">

and nothing special in the FF console (except a missing favicon.ico).
